"""
Build academic report tables and comparison charts from analysis outputs.

Inputs (generated by the analysis pipeline):
  - scripts/graph-algorithms/assortativity/results/assortativity_results.csv
  - scripts/graph-algorithms/betweeness-centrality/results/betweenness_correlation_summary.csv
  - scripts/graph-algorithms/betweeness-centrality/results/betweenness_*.csv

Outputs:
  - results/report/t1_state_panel.csv
  - results/report/t2_mesoregion_panel.csv
  - results/report/t3_heterogeneity_ranking.csv
  - results/report/t4_graph_concordance.csv
  - results/report/t5_top_bc_nodes_by_mesoregion.csv
  - results/report/*.png
"""

from __future__ import annotations

import sys
from pathlib import Path

import xml.etree.ElementTree as ET

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent.parent
REPORT_DIR = ROOT / "results" / "report"

ASSORTATIVITY_RESULTS = (
    ROOT / "scripts" / "graph-algorithms" / "assortativity" / "results" / "assortativity_results.csv"
)
BC_CORRELATION_SUMMARY = (
    ROOT
    / "scripts"
    / "graph-algorithms"
    / "betweeness-centrality"
    / "results"
    / "betweenness_correlation_summary.csv"
)
BC_RESULTS_DIR = (
    ROOT / "scripts" / "graph-algorithms" / "betweeness-centrality" / "results"
)
MESOREGION_MAPPING_CSV = ROOT / "data" / "bronze" / "ibge" / "mesoregion_municipalities.csv"
FEMICIDE_RATES_CSV = ROOT / "data" / "silver" / "taxa_feminicidio_mg_2022.csv"
REFERENCE_GRAPHML = ROOT / "data" / "gold" / "graph_mg_physical_boundaries.graphml"

sys.path.insert(0, str(ROOT / "scripts" / "graph-builders"))
from mesoregion_mapping import MESOREGION_LABELS

MESOREGION_ORDER = list(MESOREGION_LABELS.keys())
GRAPH_TYPES = ["physical_boundaries", "highways"]


def _require_file(path: Path) -> None:
    if not path.exists():
        raise FileNotFoundError(
            f"Required input not found: {path}\n"
            "Run the analysis pipeline first:\n"
            "  python3 scripts/graph-builders/build_mesoregion_subgraphs.py\n"
            "  python3 scripts/graph-algorithms/assortativity/calculate_assortativity.py\n"
            "  python3 scripts/graph-algorithms/betweeness-centrality/calculate_betweenness_centrality.py"
        )


def load_assortativity_results() -> pd.DataFrame:
    _require_file(ASSORTATIVITY_RESULTS)
    return pd.read_csv(ASSORTATIVITY_RESULTS)


def load_bc_correlation_summary() -> pd.DataFrame:
    _require_file(BC_CORRELATION_SUMMARY)
    return pd.read_csv(BC_CORRELATION_SUMMARY)


def build_t1_state_panel(
    assortativity_df: pd.DataFrame,
    bc_df: pd.DataFrame,
) -> pd.DataFrame:
    assort_state = assortativity_df[assortativity_df["scope"] == "state"][
        [
            "graph_type",
            "nodes",
            "edges",
            "pearson_r_nx",
            "pearson_p_scipy",
            "spearman_r_scipy",
            "interpretation",
        ]
    ].rename(columns={
        "nodes": "nodes_assortativity",
        "edges": "edges_assortativity",
        "pearson_r_nx": "assortativity_pearson_r",
        "pearson_p_scipy": "assortativity_pearson_p",
        "spearman_r_scipy": "assortativity_spearman_r",
        "interpretation": "assortativity_interpretation",
    })

    bc_state = bc_df[bc_df["scope"] == "state"][
        [
            "graph_type",
            "nodes",
            "edges",
            "bc_mean",
            "bc_median",
            "pearson_r",
            "pearson_p",
            "spearman_r",
            "spearman_p",
            "significant_005",
        ]
    ].rename(columns={
        "nodes": "nodes_bc",
        "edges": "edges_bc",
        "pearson_r": "bc_femicide_pearson_r",
        "pearson_p": "bc_femicide_pearson_p",
        "spearman_r": "bc_femicide_spearman_r",
        "spearman_p": "bc_femicide_spearman_p",
        "significant_005": "bc_femicide_significant_005",
    })

    panel = assort_state.merge(bc_state, on="graph_type", how="outer")
    return panel.sort_values("graph_type")


def build_t2_mesoregion_panel(
    assortativity_df: pd.DataFrame,
    bc_df: pd.DataFrame,
) -> pd.DataFrame:
    assort_meso = assortativity_df[assortativity_df["scope"] == "mesoregion"][
        [
            "graph_type",
            "mesoregion_slug",
            "mesoregion_label",
            "nodes",
            "edges",
            "pearson_r_nx",
            "pearson_p_scipy",
            "spearman_r_scipy",
            "interpretation",
        ]
    ].rename(columns={
        "nodes": "nodes_assortativity",
        "edges": "edges_assortativity",
        "pearson_r_nx": "assortativity_pearson_r",
        "pearson_p_scipy": "assortativity_pearson_p",
        "spearman_r_scipy": "assortativity_spearman_r",
        "interpretation": "assortativity_interpretation",
    })

    bc_meso = bc_df[bc_df["scope"] == "mesoregion"][
        [
            "graph_type",
            "mesoregion_slug",
            "mesoregion_label",
            "nodes",
            "edges",
            "bc_mean",
            "bc_median",
            "pearson_r",
            "pearson_p",
            "spearman_r",
            "spearman_p",
            "significant_005",
        ]
    ].rename(columns={
        "nodes": "nodes_bc",
        "edges": "edges_bc",
        "pearson_r": "bc_femicide_pearson_r",
        "pearson_p": "bc_femicide_pearson_p",
        "spearman_r": "bc_femicide_spearman_r",
        "spearman_p": "bc_femicide_spearman_p",
        "significant_005": "bc_femicide_significant_005",
    })

    panel = assort_meso.merge(
        bc_meso,
        on=["graph_type", "mesoregion_slug", "mesoregion_label"],
        how="outer",
    )
    panel["mesoregion_slug"] = pd.Categorical(
        panel["mesoregion_slug"],
        categories=MESOREGION_ORDER,
        ordered=True,
    )
    return panel.sort_values(["mesoregion_slug", "graph_type"])


def build_t3_heterogeneity_ranking(
    assortativity_df: pd.DataFrame,
    bc_df: pd.DataFrame,
) -> pd.DataFrame:
    meso_assort = assortativity_df[assortativity_df["scope"] == "mesoregion"].copy()
    meso_bc = bc_df[bc_df["scope"] == "mesoregion"].copy()

    assort_rank = meso_assort.copy()
    assort_rank["metric"] = "assortativity_pearson_r"
    assort_rank["value"] = assort_rank["pearson_r_nx"]
    assort_rank["abs_value"] = assort_rank["value"].abs()
    assort_rank["rank_within_graph_type"] = assort_rank.groupby("graph_type")["abs_value"].rank(
        ascending=False,
        method="dense",
    )

    bc_rank = meso_bc.copy()
    bc_rank["metric"] = "bc_femicide_spearman_r"
    bc_rank["value"] = bc_rank["spearman_r"]
    bc_rank["abs_value"] = bc_rank["value"].abs()
    bc_rank["rank_within_graph_type"] = bc_rank.groupby("graph_type")["abs_value"].rank(
        ascending=False,
        method="dense",
    )

    columns = [
        "graph_type",
        "mesoregion_slug",
        "mesoregion_label",
        "metric",
        "value",
        "abs_value",
        "rank_within_graph_type",
    ]
    ranking = pd.concat([assort_rank[columns], bc_rank[columns]], ignore_index=True)
    return ranking.sort_values(["metric", "graph_type", "rank_within_graph_type"])


def _same_sign(a: float, b: float) -> bool:
    if pd.isna(a) or pd.isna(b) or a == 0 or b == 0:
        return False
    return (a > 0) == (b > 0)


def build_t4_graph_concordance(
    assortativity_df: pd.DataFrame,
    bc_df: pd.DataFrame,
) -> pd.DataFrame:
    meso_assort = assortativity_df[assortativity_df["scope"] == "mesoregion"].copy()
    meso_bc = bc_df[bc_df["scope"] == "mesoregion"].copy()

    rows = []
    for meso_slug in MESOREGION_ORDER:
        label = MESOREGION_LABELS[meso_slug]
        assort_pb = meso_assort[
            (meso_assort["mesoregion_slug"] == meso_slug)
            & (meso_assort["graph_type"] == "physical_boundaries")
        ]
        assort_hw = meso_assort[
            (meso_assort["mesoregion_slug"] == meso_slug)
            & (meso_assort["graph_type"] == "highways")
        ]
        bc_pb = meso_bc[
            (meso_bc["mesoregion_slug"] == meso_slug)
            & (meso_bc["graph_type"] == "physical_boundaries")
        ]
        bc_hw = meso_bc[
            (meso_bc["mesoregion_slug"] == meso_slug)
            & (meso_bc["graph_type"] == "highways")
        ]

        assort_pb_r = assort_pb["pearson_r_nx"].squeeze() if not assort_pb.empty else np.nan
        assort_hw_r = assort_hw["pearson_r_nx"].squeeze() if not assort_hw.empty else np.nan
        bc_pb_r = bc_pb["spearman_r"].squeeze() if not bc_pb.empty else np.nan
        bc_hw_r = bc_hw["spearman_r"].squeeze() if not bc_hw.empty else np.nan

        rows.append({
            "mesoregion_slug": meso_slug,
            "mesoregion_label": label,
            "assortativity_physical_boundaries": assort_pb_r,
            "assortativity_highways": assort_hw_r,
            "assortativity_delta_hw_minus_pb": assort_hw_r - assort_pb_r,
            "assortativity_same_sign": _same_sign(assort_pb_r, assort_hw_r),
            "bc_correlation_physical_boundaries": bc_pb_r,
            "bc_correlation_highways": bc_hw_r,
            "bc_correlation_delta_hw_minus_pb": bc_hw_r - bc_pb_r,
            "bc_correlation_same_sign": _same_sign(bc_pb_r, bc_hw_r),
        })

    return pd.DataFrame(rows)


def build_t5_top_bc_nodes_by_mesoregion(top_n: int = 3) -> pd.DataFrame:
    rows = []

    for graph_type in GRAPH_TYPES:
        for meso_slug in MESOREGION_ORDER:
            graph_name = f"{graph_type}__{meso_slug}"
            csv_path = BC_RESULTS_DIR / f"betweenness_{graph_name}.csv"
            if not csv_path.exists():
                continue

            bc_df = pd.read_csv(csv_path)
            top_nodes = bc_df.sort_values("betweenness_centrality", ascending=False).head(top_n)

            for _, node_row in top_nodes.iterrows():
                rows.append({
                    "graph_type": graph_type,
                    "mesoregion_slug": meso_slug,
                    "mesoregion_label": MESOREGION_LABELS[meso_slug],
                    "rank": int(node_row["bc_rank"]),
                    "node_id": node_row["node_id"],
                    "city": node_row["city"] if pd.notna(node_row["city"]) else node_row["node_id"],
                    "betweenness_centrality": node_row["betweenness_centrality"],
                    "femicide_rate_normalized": node_row["femicide_rate_normalized"],
                })

    if not rows:
        print("[WARNING] No mesoregion betweenness CSV files found for T5.")

    return pd.DataFrame(rows)


def _load_municipality_geocodes() -> pd.DataFrame:
    if not REFERENCE_GRAPHML.exists():
        return pd.DataFrame(columns=["municipality", "geocodigo"])

    graphml_ns = "http://graphml.graphdrawing.org/xmlns"
    root = ET.parse(REFERENCE_GRAPHML).getroot()
    rows = []
    for node in root.findall(f".//{{{graphml_ns}}}node"):
        municipality = node.get("id")
        geocodigo = None
        for data in node.findall(f"{{{graphml_ns}}}data"):
            if data.get("key") == "d0":
                geocodigo = data.text
                break
        rows.append({"municipality": municipality, "geocodigo": geocodigo})
    return pd.DataFrame(rows)


def plot_heatmap(
    df: pd.DataFrame,
    value_column: str,
    title: str,
    output_path: Path,
    center: float = 0.0,
) -> None:
    meso_df = df[df["scope"] == "mesoregion"].copy()
    if meso_df.empty:
        print(f"[WARNING] Skipping heatmap (no mesoregion data): {output_path.name}")
        return

    pivot = meso_df.pivot(index="mesoregion_slug", columns="graph_type", values=value_column)
    pivot = pivot.reindex(MESOREGION_ORDER).dropna(how="all")
    pivot.index = [MESOREGION_LABELS[slug] for slug in pivot.index]

    fig, axis = plt.subplots(figsize=(8, 10))
    matrix = pivot.values.astype(float)
    vmax = np.nanmax(np.abs(matrix))
    if np.isnan(vmax) or vmax == 0:
        vmax = 1.0

    image = axis.imshow(matrix, aspect="auto", cmap="RdBu_r", vmin=-vmax, vmax=vmax)
    axis.set_xticks(range(len(pivot.columns)))
    axis.set_xticklabels([col.replace("_", " ") for col in pivot.columns])
    axis.set_yticks(range(len(pivot.index)))
    axis.set_yticklabels(pivot.index)
    axis.set_title(title)

    for row_index in range(matrix.shape[0]):
        for col_index in range(matrix.shape[1]):
            value = matrix[row_index, col_index]
            if not np.isnan(value):
                axis.text(
                    col_index,
                    row_index,
                    f"{value:.3f}",
                    ha="center",
                    va="center",
                    color="black",
                    fontsize=8,
                )

    plt.colorbar(image, ax=axis, shrink=0.8)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Saved: {output_path}")


def plot_state_vs_mesoregion_scatter(
    df: pd.DataFrame,
    value_column: str,
    title: str,
    ylabel: str,
    output_path: Path,
) -> None:
    meso_df = df[df["scope"] == "mesoregion"].copy()
    state_df = df[df["scope"] == "state"].copy()
    if meso_df.empty or state_df.empty:
        print(f"[WARNING] Skipping scatter (missing state or mesoregion data): {output_path.name}")
        return

    fig, axes = plt.subplots(1, 2, figsize=(14, 6), sharey=True)

    for axis, graph_type in zip(axes, GRAPH_TYPES):
        state_value = state_df.loc[state_df["graph_type"] == graph_type, value_column]
        if state_value.empty:
            continue
        state_value = float(state_value.squeeze())

        subset = meso_df[meso_df["graph_type"] == graph_type]
        axis.scatter(
            [state_value] * len(subset),
            subset[value_column],
            alpha=0.8,
            s=50,
            color="#2b7bba",
            edgecolors="white",
        )

        for _, row in subset.iterrows():
            axis.annotate(
                row["mesoregion_label"].split()[0],
                (state_value, row[value_column]),
                fontsize=7,
                alpha=0.75,
                xytext=(4, 4),
                textcoords="offset points",
            )

        lims = [
            min(state_value, subset[value_column].min()) - 0.05,
            max(state_value, subset[value_column].max()) + 0.05,
        ]
        axis.plot(lims, lims, "k--", alpha=0.4, linewidth=1)
        axis.set_xlim(lims)
        axis.set_ylim(lims)
        axis.set_xlabel("State-level value")
        axis.set_ylabel(ylabel)
        axis.set_title(graph_type.replace("_", " "))
        axis.grid(True, alpha=0.3)

    fig.suptitle(title, fontsize=12)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Saved: {output_path}")


def plot_femicide_rate_violin_by_mesoregion(output_path: Path) -> None:
    if not MESOREGION_MAPPING_CSV.exists() or not FEMICIDE_RATES_CSV.exists():
        print("[WARNING] Skipping femicide rate violin (mapping or rates CSV missing).")
        return

    mapping_df = pd.read_csv(MESOREGION_MAPPING_CSV)
    rates_df = pd.read_csv(FEMICIDE_RATES_CSV)
    geocodes_df = _load_municipality_geocodes()

    merged = mapping_df.merge(geocodes_df, on="municipality", how="left")
    merged["geocodigo"] = merged["geocodigo"].astype(str).str.strip()
    rates_df["municipio_cod"] = rates_df["municipio_cod"].astype(str).str.strip()
    merged = merged.merge(
        rates_df,
        left_on="geocodigo",
        right_on="municipio_cod",
        how="left",
    )
    if "taxa_feminicidio_normalizada" not in merged.columns:
        print("[WARNING] Skipping femicide rate violin (normalized rate column missing).")
        return

    merged["taxa_feminicidio_normalizada"] = pd.to_numeric(
        merged["taxa_feminicidio_normalizada"],
        errors="coerce",
    )
    merged = merged.dropna(subset=["taxa_feminicidio_normalizada"])
    merged["mesoregion_slug"] = pd.Categorical(
        merged["mesoregion_slug"],
        categories=MESOREGION_ORDER,
        ordered=True,
    )
    merged = merged.sort_values("mesoregion_slug")

    labels = [MESOREGION_LABELS[slug] for slug in MESOREGION_ORDER if slug in set(merged["mesoregion_slug"])]
    data = [
        merged.loc[merged["mesoregion_label"] == label, "taxa_feminicidio_normalizada"].values
        for label in labels
    ]

    fig, axis = plt.subplots(figsize=(14, 6))
    parts = axis.violinplot(data, showmeans=True, showmedians=True)

    for body in parts["bodies"]:
        body.set_facecolor("#2b7bba")
        body.set_alpha(0.65)

    axis.set_xticks(range(1, len(labels) + 1))
    axis.set_xticklabels(labels, rotation=45, ha="right")
    axis.set_ylabel("Normalized femicide rate")
    axis.set_title("Distribution of Normalized Femicide Rates by Mesoregion")
    axis.grid(True, alpha=0.3, axis="y")
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Saved: {output_path}")


def save_tables(tables: dict[str, pd.DataFrame]) -> None:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    for name, dataframe in tables.items():
        if dataframe.empty:
            print(f"[WARNING] Table {name} is empty — skipping CSV export.")
            continue
        output_path = REPORT_DIR / f"{name}.csv"
        dataframe.to_csv(output_path, index=False, float_format="%.6f")
        print(f"Saved: {output_path}")


def generate_report() -> None:
    assortativity_df = load_assortativity_results()
    bc_df = load_bc_correlation_summary()

    tables = {
        "t1_state_panel": build_t1_state_panel(assortativity_df, bc_df),
        "t2_mesoregion_panel": build_t2_mesoregion_panel(assortativity_df, bc_df),
        "t3_heterogeneity_ranking": build_t3_heterogeneity_ranking(assortativity_df, bc_df),
        "t4_graph_concordance": build_t4_graph_concordance(assortativity_df, bc_df),
        "t5_top_bc_nodes_by_mesoregion": build_t5_top_bc_nodes_by_mesoregion(top_n=3),
    }
    save_tables(tables)

    REPORT_DIR.mkdir(parents=True, exist_ok=True)

    plot_heatmap(
        assortativity_df,
        value_column="pearson_r_nx",
        title="Assortativity by Mesoregion and Graph Type",
        output_path=REPORT_DIR / "heatmap_assortativity.png",
    )
    plot_heatmap(
        bc_df,
        value_column="spearman_r",
        title="BC vs Femicide Rate (Spearman r) by Mesoregion",
        output_path=REPORT_DIR / "heatmap_bc_correlation.png",
    )
    plot_state_vs_mesoregion_scatter(
        assortativity_df,
        value_column="pearson_r_nx",
        title="Assortativity: State vs Mesoregion",
        ylabel="Mesoregion assortativity (Pearson r)",
        output_path=REPORT_DIR / "scatter_assortativity_state_vs_mesoregion.png",
    )
    plot_state_vs_mesoregion_scatter(
        bc_df,
        value_column="spearman_r",
        title="BC–Femicide Correlation: State vs Mesoregion",
        ylabel="Mesoregion Spearman r",
        output_path=REPORT_DIR / "scatter_bc_correlation_state_vs_mesoregion.png",
    )
    plot_femicide_rate_violin_by_mesoregion(
        REPORT_DIR / "violin_femicide_rate_by_mesoregion.png",
    )

    print(f"\nReport artifacts written to: {REPORT_DIR}")


def main() -> None:
    generate_report()


if __name__ == "__main__":
    main()
